### ISSUE TITLE
css 实现按钮固定在底部

### ISSUE THREAD

**Issue by Zhaohb2017** [Zhaohb2017/test_platform_front#5]
### CSS代码如下
```CSS
<style>
.r{position:fixed; bottom:0;}
</style>
```
### HTML代码如下
```html
<div>
    <div class="r">
        <input type="submit" value="确认添加"  class="btn btn-primary"/>
    </div>
</div>
```
### 备注
使用CSS代码就可以实现了（.r{position:fixed; bottom:0;}）
